[2024-02-26 23:54:39,302] {processor.py:153} INFO - Started process (PID=1458) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:54:39,304] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:54:39,305] {logging_mixin.py:115} INFO - [2024-02-26 23:54:39,305] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:54:39,520] {logging_mixin.py:115} INFO - [2024-02-26 23:54:39,517] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag_entrega_3 copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_entrega_3 copy.py", line 32, in <module>
    start_date=days_ago(2),
NameError: name 'days_ago' is not defined
[2024-02-26 23:54:39,521] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:54:39,538] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.238 seconds
[2024-02-26 23:54:50,061] {processor.py:153} INFO - Started process (PID=1510) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:54:50,065] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:54:50,068] {logging_mixin.py:115} INFO - [2024-02-26 23:54:50,067] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:54:50,540] {logging_mixin.py:115} INFO - [2024-02-26 23:54:50,537] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag_entrega_3 copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_entrega_3 copy.py", line 32, in <module>
    start_date=days_ago(2),
NameError: name 'days_ago' is not defined
[2024-02-26 23:54:50,542] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:54:50,565] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.511 seconds
[2024-02-26 23:55:01,372] {processor.py:153} INFO - Started process (PID=1562) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:01,374] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:55:01,375] {logging_mixin.py:115} INFO - [2024-02-26 23:55:01,375] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:01,713] {logging_mixin.py:115} INFO - [2024-02-26 23:55:01,710] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag_entrega_3 copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_entrega_3 copy.py", line 32, in <module>
    start_date=days_ago(2),
NameError: name 'days_ago' is not defined
[2024-02-26 23:55:01,715] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:01,736] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.368 seconds
[2024-02-26 23:55:12,323] {processor.py:153} INFO - Started process (PID=1614) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:12,325] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:55:12,327] {logging_mixin.py:115} INFO - [2024-02-26 23:55:12,327] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:12,686] {logging_mixin.py:115} INFO - [2024-02-26 23:55:12,683] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag_entrega_3 copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_entrega_3 copy.py", line 32, in <module>
    start_date=days_ago(2),
NameError: name 'days_ago' is not defined
[2024-02-26 23:55:12,687] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:12,711] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.392 seconds
[2024-02-26 23:55:23,262] {processor.py:153} INFO - Started process (PID=1666) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:23,264] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:55:23,266] {logging_mixin.py:115} INFO - [2024-02-26 23:55:23,266] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:23,527] {logging_mixin.py:115} INFO - [2024-02-26 23:55:23,525] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag_entrega_3 copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_entrega_3 copy.py", line 32, in <module>
    start_date=days_ago(2),
NameError: name 'days_ago' is not defined
[2024-02-26 23:55:23,529] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:23,547] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.292 seconds
[2024-02-26 23:55:34,152] {processor.py:153} INFO - Started process (PID=1718) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:34,155] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:55:34,156] {logging_mixin.py:115} INFO - [2024-02-26 23:55:34,156] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:34,470] {logging_mixin.py:115} INFO - [2024-02-26 23:55:34,467] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag_entrega_3 copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_entrega_3 copy.py", line 32, in <module>
    start_date=days_ago(2),
NameError: name 'days_ago' is not defined
[2024-02-26 23:55:34,472] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:55:34,490] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.343 seconds
[2024-02-26 23:59:46,962] {processor.py:153} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:59:46,964] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:59:46,966] {logging_mixin.py:115} INFO - [2024-02-26 23:59:46,966] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:59:47,435] {processor.py:651} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl']) retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:59:47,620] {logging_mixin.py:115} INFO - [2024-02-26 23:59:47,620] {manager.py:508} INFO - Created Permission View: can delete on DAG:tutorial_taskflow_api_etl
[2024-02-26 23:59:47,637] {logging_mixin.py:115} INFO - [2024-02-26 23:59:47,637] {manager.py:508} INFO - Created Permission View: can edit on DAG:tutorial_taskflow_api_etl
[2024-02-26 23:59:47,646] {logging_mixin.py:115} INFO - [2024-02-26 23:59:47,645] {manager.py:508} INFO - Created Permission View: can read on DAG:tutorial_taskflow_api_etl
[2024-02-26 23:59:47,648] {logging_mixin.py:115} INFO - [2024-02-26 23:59:47,647] {dag.py:2420} INFO - Sync 1 DAGs
[2024-02-26 23:59:47,659] {logging_mixin.py:115} INFO - [2024-02-26 23:59:47,659] {dag.py:2439} INFO - Creating ORM DAG for tutorial_taskflow_api_etl
[2024-02-26 23:59:47,669] {logging_mixin.py:115} INFO - [2024-02-26 23:59:47,669] {dag.py:2972} INFO - Setting next_dagrun for tutorial_taskflow_api_etl to None, run_after=None
[2024-02-26 23:59:47,688] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.729 seconds
[2024-02-26 23:59:58,290] {processor.py:153} INFO - Started process (PID=224) to work on /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:59:58,292] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag_entrega_3 copy.py for tasks to queue
[2024-02-26 23:59:58,294] {logging_mixin.py:115} INFO - [2024-02-26 23:59:58,293] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:59:58,759] {processor.py:651} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl']) retrieved from /opt/airflow/dags/dag_entrega_3 copy.py
[2024-02-26 23:59:58,775] {logging_mixin.py:115} INFO - [2024-02-26 23:59:58,775] {dag.py:2420} INFO - Sync 1 DAGs
[2024-02-26 23:59:58,791] {logging_mixin.py:115} INFO - [2024-02-26 23:59:58,791] {dag.py:2972} INFO - Setting next_dagrun for tutorial_taskflow_api_etl to None, run_after=None
[2024-02-26 23:59:58,800] {processor.py:161} INFO - Processing /opt/airflow/dags/dag_entrega_3 copy.py took 0.516 seconds
